In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
df=pd.read_csv("covid_toy.csv")

In [2]:
df.head(4)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No

In [3]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [5]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [6]:
for i in df.columns:
    if df[i].dtype=="object":
        print(df[i].value_counts())

gender
Female    59
Male      41
Name: count, dtype: int64
cough
Mild      62
Strong    38
Name: count, dtype: int64
city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64
has_covid
No     55
Yes    45
Name: count, dtype: int64


Gender->Onehot
Fever->Simple imputer
cough->Ordinal
city->ohe


In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

Without using column transformer

In [8]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[["fever"]])

X_test_fever=si.fit_transform(X_test[["fever"]])

In [9]:
X_train_fever

array([[101.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [100.        ],
       [103.        ],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [100.77777778],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [100.77777778],
       [104.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [100.77777778],
       [100.        ],
       [ 99.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [103.        ],
       [104.        ],
       [104.        ],
       [100.77777778],
       [102.        ],
       [100.77777778],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 99.        ],
       [100.77777778],
       [104.        ],
       [100.77777778],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [ 98

In [10]:
oe=OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough=oe.fit_transform(X_train[["cough"]])

X_test_cough=oe.fit_transform(X_test[["cough"]])

In [11]:
X_test_cough

array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [12]:
ohe=OneHotEncoder(drop="first",sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[["gender","city"]])
X_test_gender_city=ohe.fit_transform(X_train[["gender","city"]])

In [13]:
X_train_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],


In [14]:
X_train_age=X_train.drop(columns=["gender","fever","cough","city"]).values

X_test_age=X_test.drop(columns=["gender","fever","cough","city"]).values

In [15]:
X_train_age.shape

(80, 1)

In [18]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 20 and the array at index 2 has size 80

Using Column transformer

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        ("tnf1", SimpleImputer(), ["fever"]),
        ("tnf2", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"]),
        ("tnf3", OneHotEncoder(sparse_output=False, drop="first"), ["gender", "city"])
    ],
    remainder="passthrough"
)


In [25]:
transformer.fit_transform(X_train)

array([[101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.    

In [26]:
transformer.transform(X_test).shape

(20, 7)