In [72]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [60]:
df=pd.read_csv("train.csv")

In [61]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [62]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [63]:
df.drop(columns=['Name','Ticket','Cabin',"PassengerId"],inplace=True)

In [64]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [65]:
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])

In [66]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

In [67]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [68]:
df["Sex"]=pd.get_dummies(df["Sex"],drop_first=True)

In [69]:
df

Survived  Pclass    Sex   Age  SibSp  Parch     Fare Embarked
0           0       3   True  22.0      1      0   7.2500        S
1           1       1  False  38.0      1      0  71.2833        C
2           1       3  False  26.0      0      0   7.9250        S
3           1       1  False  35.0      1      0  53.1000        S
4           0       3   True  35.0      0      0   8.0500        S
..        ...     ...    ...   ...    ...    ...      ...      ...
886         0       2   True  27.0      0      0  13.0000        S
887         1       1  False  19.0      0      0  30.0000        S
888         0       3  False   NaN      1      2  23.4500        S
889         1       1   True  26.0      0      0  30.0000        C
890         0       3   True  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [76]:
tf= ColumnTransformer(
    [("OHE",OneHotEncoder(sparse_output=False,drop="first"),["Embarked"]),
    ("KNN",KNNImputer(),["Age"])],
    remainder="passthrough")

In [77]:
df

Survived  Pclass    Sex   Age  SibSp  Parch     Fare Embarked
0           0       3   True  22.0      1      0   7.2500        S
1           1       1  False  38.0      1      0  71.2833        C
2           1       3  False  26.0      0      0   7.9250        S
3           1       1  False  35.0      1      0  53.1000        S
4           0       3   True  35.0      0      0   8.0500        S
..        ...     ...    ...   ...    ...    ...      ...      ...
886         0       2   True  27.0      0      0  13.0000        S
887         1       1  False  19.0      0      0  30.0000        S
888         0       3  False   NaN      1      2  23.4500        S
889         1       1   True  26.0      0      0  30.0000        C
890         0       3   True  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [81]:
X=df.iloc[:,1:]
y=df.iloc[:,0]

In [79]:
X

Pclass    Sex   Age  SibSp  Parch     Fare Embarked
0         3   True  22.0      1      0   7.2500        S
1         1  False  38.0      1      0  71.2833        C
2         3  False  26.0      0      0   7.9250        S
3         1  False  35.0      1      0  53.1000        S
4         3   True  35.0      0      0   8.0500        S
..      ...    ...   ...    ...    ...      ...      ...
886       2   True  27.0      0      0  13.0000        S
887       1  False  19.0      0      0  30.0000        S
888       3  False   NaN      1      2  23.4500        S
889       1   True  26.0      0      0  30.0000        C
890       3   True  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [82]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [83]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [87]:
X_train

Pclass    Sex   Age  SibSp  Parch      Fare Embarked
331       1   True  45.5      0      0   28.5000        S
733       2   True  23.0      0      0   13.0000        S
382       3   True  32.0      0      0    7.9250        S
704       3   True  26.0      1      0    7.8542        S
813       3  False   6.0      4      2   31.2750        S
..      ...    ...   ...    ...    ...       ...      ...
106       3  False  21.0      0      0    7.6500        S
270       1   True   NaN      0      0   31.0000        S
860       3   True  41.0      2      0   14.1083        S
435       1  False  14.0      1      2  120.0000        S
102       1   True  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [84]:
X_train_trf=tf.fit_transform(X_train)

In [86]:
X_train_trf.shape

(712, 8)

In [88]:
X_test_trf=tf.transform(X_test)

In [89]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [113]:
from sklearn.ensemble import BaggingClassifier
clf=BaggingClassifier(n_estimators=10000)
clf.fit(X_train_trf,y_train)

BaggingClassifier(n_estimators=10000)

In [114]:
clf.score(X_test_trf,y_test)

0.8044692737430168

In [91]:
rfc.fit(X_train_trf,y_train)

RandomForestClassifier()

In [92]:
rfc.score(X_test_trf,y_test)

0.8212290502793296

In [93]:
X_trf=tf.fit_transform(X)

In [94]:
X_train_trf

array([[0.0, 1.0, 45.5, ..., 0, 0, 28.5],
       [0.0, 1.0, 23.0, ..., 0, 0, 13.0],
       [0.0, 1.0, 32.0, ..., 0, 0, 7.925],
       ...,
       [0.0, 1.0, 41.0, ..., 2, 0, 14.1083],
       [0.0, 1.0, 14.0, ..., 1, 2, 120.0],
       [0.0, 1.0, 21.0, ..., 0, 1, 77.2875]], dtype=object)

In [96]:
scaler=StandardScaler()

X_train_trf2= scaler.fit_transform(X_train_trf)

X_test_trf2 =scaler.transform(X_test_trf)

In [97]:
X_train_trf2

array([[-0.30335547,  0.59248936,  1.2322632 , ..., -0.47072241,
        -0.47934164, -0.07868358],
       [-0.30335547,  0.59248936, -0.50048197, ..., -0.47072241,
        -0.47934164, -0.37714494],
       [-0.30335547,  0.59248936,  0.1926161 , ..., -0.47072241,
        -0.47934164, -0.47486697],
       ...,
       [-0.30335547,  0.59248936,  0.88571416, ...,  1.23056874,
        -0.47934164, -0.35580399],
       [-0.30335547,  0.59248936, -1.19358003, ...,  0.37992316,
         2.04874166,  1.68320121],
       [-0.30335547,  0.59248936, -0.65450376, ..., -0.47072241,
         0.78470001,  0.86074761]])

In [102]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
X_train_pca=pca.fit_transform(X_train_trf2)
X_test_pca=pca.transform(X_test_trf2)

In [103]:
pca.explained_variance_ratio_

array([0.23004728, 0.21352766, 0.19232468])

In [104]:
np.cumsum(pca.explained_variance_ratio_)

array([0.23004728, 0.44357494, 0.63589961])

In [105]:
X_train_pca

array([[ 0.06684484,  1.92009611,  0.84718115],
       [-0.55018617,  0.27032568,  0.83820119],
       [-1.11610458, -0.02724052,  0.9324152 ],
       ...,
       [-0.45328235, -0.37376063,  0.91019412],
       [ 3.29305808, -0.42035175, -0.20271468],
       [ 1.21701722,  0.69053648,  0.55258049]])

In [108]:
import plotly.express as px
y_train_trf=y_train.astype(str)
fig =px.scatter_3d(x=X_train_pca[:,0],y=X_train_pca[:,1],z=X_train_pca[:,2],color=y_train_trf)
fig.show()